language: python

python: 
  - "3.6"

env:
  global:
    - "APP_SETTINGS=test_db"

install:
  - "pip install -r requirements.txt"

before script:
  - "psql -c 'create database test_db;' -U postgres"

script:
  - python -m pytest --cov
  
after_success:
  - coveralls